//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ndtlesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ketqua
    {
        public int MaSV { get; set; }
        public int MaMH { get; set; }
        public Nullable<decimal> Diem { get; set; }
    
        public virtual Monhoc Monhoc { get; set; }
    }
}
