//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ndtlesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int MaSv { get; set; }
        public string HoSV { get; set; }
        public string TenSV { get; set; }
        public string Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public Nullable<int> MaKh { get; set; }
        public Nullable<decimal> HocBong { get; set; }
        public Nullable<decimal> DiemTrungBinh { get; set; }
    }
}
