//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdtLesson07Db.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NdtK22CNTT4Lesson07DbEntities : DbContext
    {
        public NdtK22CNTT4Lesson07DbEntities()
            : base("name=NdtK22CNTT4Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NdtKhoa> NdtKhoas { get; set; }
        public virtual DbSet<NdtSinhVien> NdtSinhViens { get; set; }
    }
}
