//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdtK22CNT4Lesson11_2210900071.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NdtK22CNT4Lesson11DbEntities : DbContext
    {
        public NdtK22CNT4Lesson11DbEntities()
            : base("name=NdtK22CNT4Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NdtCategory> NdtCategories { get; set; }
        public virtual DbSet<NdtProduct> NdtProducts { get; set; }
    }
}
