//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdtK22CNT4Lesson11_2210900071.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NdtProduct
    {
        public int Ndtid2210900071 { get; set; }
        public string NdtProName { get; set; }
        public Nullable<int> NdtQty { get; set; }
        public Nullable<double> NdtPrice { get; set; }
        public Nullable<int> NdtCateId { get; set; }
        public Nullable<bool> NdtActive { get; set; }
    }
}
