//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenDanhTruong_2210900071.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDT_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NDT_TACGIA()
        {
            this.NDT_SACH = new HashSet<NDT_SACH>();
        }
    
        public string Ndt_MaTG { get; set; }
        public string Ndt_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NDT_SACH> NDT_SACH { get; set; }
    }
}
