//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenDanhTruong_2210900071.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDT_SACH
    {
        public int Ndt_MaSach { get; set; }
        public string Ndt_TenSach { get; set; }
        public Nullable<int> Ndt_SoTrang { get; set; }
        public Nullable<int> Ndt_NamXB { get; set; }
        public string Ndt_MaTG { get; set; }
        public Nullable<bool> Ndt_TrangThai { get; set; }
    
        public virtual NDT_TACGIA NDT_TACGIA { get; set; }
    }
}
