//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NdtK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NdtAccount
    {
        public int NdtID { get; set; }
        public string NdtUseName { get; set; }
        public string NdtPassword { get; set; }
        public string NdtFullName { get; set; }
        public string NdtEmail { get; set; }
        public string NdtPhone { get; set; }
        public Nullable<bool> NdtActive { get; set; }
    }
}
